[package]
name = "c-cargo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.154"
toml = "0.7.2"

[profile.release]
strip = true
lto = true
codegen-units = 1
